# Generated by Django 2.2.5 on 2019-09-28 22:20

from django.db import migrations, models
import iban.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', iban.models.IBANField(max_length=27)),
            ],
        ),
    ]
